# This definition creates a k8s service account for automatic deployment
# in namespace "default"
#
# Usage:
#   kubectl apply -f $file
#
# Validation:
#   kubectl --namespace=default --as system:serviceaccount:default:deploy-in-default-npa auth can-i create deployments
#
# See also:
#   https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/
---
# 1. Create a service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploy-in-default-npa
  namespace: default
---
# 2. Create a role with deployment permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: default-deploy
rules:
- apiGroups: ["extensions"]
  resources: ["deployments"]
  verbs: ["get","list","patch","update", "create"]
---
# 3. Assign role to service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-default-deploy
  namespace: default
roleRef:
  kind: Role
  name: default-deploy
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: deploy-in-default-npa
  kind: ServiceAccount
  namespace: default
